// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncService.Data;

#nullable disable

namespace SyncService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SyncService.Models.AppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("PostTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PostTimeDateTime")
                        .HasColumnType("datetime(0)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AppNotifications");
                });

            modelBuilder.Entity("SyncService.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasDelivered")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasSeen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SendTo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SentFrom")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampDateTime")
                        .HasColumnType("datetime(0)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("SyncService.Models.CallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CallStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CallType")
                        .HasColumnType("int");

                    b.Property<string>("CalleeNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CallerNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampDateTime")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.ToTable("CallLogs");
                });

            modelBuilder.Entity("SyncService.Models.DeviceIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("LastSeen")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSeenDateTime")
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.ToTable("DeviceIdentifiers");
                });

            modelBuilder.Entity("SyncService.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DateSent")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateSentDateTime")
                        .HasColumnType("datetime(0)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SyncService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
